name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: base
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/base.svg
          token: ${{ secrets.TOKEN }}
          # Options
          user: IjichiSeika
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
      - name: Organization introduction
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/introduction.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: IjichiSeika
          base: header
          plugin_introduction: yes
          plugin_introduction_title: yes
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: Using graph charts
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph
      - name: Recently played games
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/steam.svg
          base: ""
          plugin_steam: yes
          plugin_steam_achievements_limit: 2
          plugin_steam_games_limit: 1
          plugin_steam_playtime_threshold: 2
          plugin_steam_recent_games_limit: 1
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_user: 76561198000697560
